### PR TITLE
Updates for OBS 30 / v5.0.4

### PR DESCRIPTION
**Pull request by GeorgesStavracas**
See commits

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
Seems like the build is failing because it's trying to pull in the `libuiohook` submodule during the build step, and Flathub disallows networking while building. An alternative is to put the `libuiohook` dep as a module in the manifest.

**Comment by HugLifeTiZ** [comment]
Thanks so much for picking up the ball I dropped here so long ago. I remember running into some similar nonsense with libuiohook when I initially made this package so long ago. I don't quite remember how I fixed it, though. Since you have been so kind as to get the ball rolling on this, I'll see what I can do about getting a libuiohook module in the manifest. Can't be worse than geany-plugins!

**Comment by tytan652** [comment]
The libuiohook submodule points to a commit only present in the univrsal
fork of the project.

So I made a fix
https://github.com/tytan652/com.obsproject.Studio.Plugin.InputOverlay/commit/ea4121f0cce2daae80c2e6574754979a1276c8d0

**Comment by TiZ-HugLife** [comment]
I'm very sorry for having left this to languish as long as I did. Huge thanks for the work you both did on getting this updated.

**Pull request merged**
